/**
 * Fixture app exercising the `Auth0FgaApi` source shape (`@auth0/fga`, deprecated --
 * code-mapping.md's "Detecting the source shape": keyed on an `environment` string
 * instead of an `apiUrl`, generated by the same tooling lineage as `OpenFgaApi`, so
 * "once detected, convert it exactly as `OpenFgaApi`" -- recognizing it from its
 * constructor and `environment` key is the only `Auth0FgaApi`-specific step).
 * `Auth0FgaApi extends OpenFgaApi` directly (`@auth0/fga/dist/api.d.ts`); every call
 * below is identical in shape to openfga-api/src/original/app.ts.
 *
 * TEST HARNESS ONLY, not a code-mapping concern: `@auth0/fga`'s `Configuration`
 * (`dist/configuration.js`) hardcodes `apiUrl` from a fixed `environment` lookup
 * table with no public constructor override -- real usage always points at a hosted
 * Auth0/Okta FGA endpoint. To get a live signal from this deprecated SDK against a
 * local OpenFGA container for this fixture, `environment: "playground"` (the one
 * value with `allowNoAuth: true`, so no clientId/clientSecret are required) is
 * constructed normally and then the resulting `configuration.apiUrl` -- a plain
 * mutable property, confirmed reading `dist/configuration.js:38-39`'s
 * `getBasePath()` -- is overwritten to point at the local container. A real
 * application never does this; it is the harness's substitute for pointing a
 * deprecated, hosted-only SDK at a disposable test server.
 */
import { Auth0FgaApi, Configuration, type UserConfigurationParams } from "@auth0/fga";
import { emit, type TupleSummary } from "../../../shared/report.ts";

const API_URL = process.env.FGA_API_URL || "http://localhost:28091";
const STORE_ID = process.env.FGA_STORE_ID as string;

if (!STORE_ID) {
  throw new Error("FGA_STORE_ID must be set in the environment");
}

// `UserConfigurationParams`'s type requires clientId/clientSecret unconditionally,
// even though `environment: "playground"` sets `allowNoAuth: true` at runtime
// (`dist/configuration.js`'s `if (!environmentConfiguration.allowNoAuth)` gate) --
// the .d.ts is stricter than the actual runtime rule for this one environment.
// The type assertion below is deliberate, not a shortcut around a real error:
// supplying placeholder clientId/clientSecret values instead would be worse, not
// safer -- `Configuration`'s own logic activates the real OAuth client-credentials
// flow whenever `clientId || clientSecret` is truthy, regardless of `allowNoAuth`,
// which would make this fixture call a real Auth0 tenant and fail authentication
// rather than actually exercising the no-auth path this SDK version supports.
const config = new Configuration({ storeId: STORE_ID, environment: "playground" } as UserConfigurationParams);
// TEST HARNESS ONLY -- see file header.
(config as unknown as { apiUrl: string }).apiUrl = API_URL;

const raw = new Auth0FgaApi(config);

function unwrap<T>(resp: T | { body: T }): T {
  return (resp as { body?: T }).body ?? (resp as T);
}

async function main() {
  // ------------------------------------------------------------------
  // check
  // ------------------------------------------------------------------
  const checkResp = unwrap(
    await raw.check(STORE_ID, { tuple_key: { user: "user:bob", relation: "viewer", object: "document:1" } }),
  );
  emit({ op: "check", label: "check:bob-viewer", allowed: !!checkResp.allowed });

  // ------------------------------------------------------------------
  // write (unconditioned) + check
  // ------------------------------------------------------------------
  await raw.write(STORE_ID, { writes: { tuple_keys: [{ user: "user:carol", relation: "viewer", object: "document:1" }] } });
  const carolResp = unwrap(
    await raw.check(STORE_ID, { tuple_key: { user: "user:carol", relation: "viewer", object: "document:1" } }),
  );
  emit({ op: "check", label: "check:carol-viewer-after-write", allowed: !!carolResp.allowed });

  // ------------------------------------------------------------------
  // write (conditioned on is_active=false) + check
  // ------------------------------------------------------------------
  await raw.write(STORE_ID, {
    writes: {
      tuple_keys: [
        {
          user: "user:dave",
          relation: "viewer",
          object: "document:1",
          condition: { name: "is_active", context: { active: false } },
        },
      ],
    },
  });
  const daveResp = unwrap(
    await raw.check(STORE_ID, { tuple_key: { user: "user:dave", relation: "viewer", object: "document:1" } }),
  );
  emit({ op: "check", label: "check:dave-viewer-inactive-caveat", allowed: !!daveResp.allowed });

  // ------------------------------------------------------------------
  // write with a USERSET-typed subject (group:eng#member, not a plain user) + check.
  // Neither of the two writes above ever exercises this subject shape -- the only
  // group#member relationship in this fixture was, before this addition, static seed
  // data (shared/seed-relationships.json), never something a write() call produced.
  // A new object (document:2) keeps this isolated from every other label's expected
  // value above.
  // ------------------------------------------------------------------
  await raw.write(STORE_ID, { writes: { tuple_keys: [{ user: "group:eng#member", relation: "viewer", object: "document:2" }] } });
  const anneDoc2Resp = unwrap(
    await raw.check(STORE_ID, { tuple_key: { user: "user:anne", relation: "viewer", object: "document:2" } }),
  );
  emit({ op: "check", label: "check:anne-viewer-document2-via-group-write", allowed: !!anneDoc2Resp.allowed });

  // ------------------------------------------------------------------
  // batchCheck -- raw wire response, a map keyed by correlation_id.
  // ------------------------------------------------------------------
  const batchResp = unwrap(
    await raw.batchCheck(STORE_ID, {
      checks: [
        { tuple_key: { user: "user:bob", relation: "viewer", object: "document:1" }, correlation_id: "req-bob-viewer" },
        { tuple_key: { user: "user:anne", relation: "viewer", object: "document:1" }, correlation_id: "req-anne-viewer" },
        { tuple_key: { user: "user:anne", relation: "writer", object: "document:1" }, correlation_id: "req-anne-writer" },
      ],
    }),
  );
  for (const label of ["req-bob-viewer", "req-anne-viewer", "req-anne-writer"]) {
    const result = batchResp.result?.[label];
    emit({ op: "batchCheck", label: `batchCheck:${label}`, allowed: !!result?.allowed });
  }

  // ------------------------------------------------------------------
  // listObjects -- which documents can anne view?
  // ------------------------------------------------------------------
  const listObjectsResp = unwrap(
    await raw.listObjects(STORE_ID, { type: "document", relation: "viewer", user: "user:anne" }),
  );
  const objectIds = listObjectsResp.objects.map((o) => o.split(":")[1]).sort();
  emit({ op: "listObjects", label: "listObjects:anne-viewer", objects: objectIds });

  // ------------------------------------------------------------------
  // listUsers -- which users can view document:1?
  // ------------------------------------------------------------------
  const listUsersResp = unwrap(
    await raw.listUsers(STORE_ID, {
      object: { type: "document", id: "1" },
      relation: "viewer",
      user_filters: [{ type: "user" }],
    }),
  );
  const userIds = listUsersResp.users.map((u) => u.object!.id).sort();
  emit({ op: "listUsers", label: "listUsers:document1-viewer", users: userIds });

  // ------------------------------------------------------------------
  // read -- every viewer tuple stored directly on document:1
  // ------------------------------------------------------------------
  const readResp = unwrap(await raw.read(STORE_ID, { tuple_key: { object: "document:1", relation: "viewer" } }));
  const tuples: TupleSummary[] = readResp.tuples
    .map((t): TupleSummary => {
      const [subjectType, rest] = t.key.user.split(":");
      const [subjectId, subjectRelation] = rest.split("#");
      return {
        subjectType,
        subjectId,
        subjectRelation: subjectRelation || undefined,
        conditioned: !!t.key.condition,
      };
    })
    .sort((a, b) => (a.subjectId + (a.subjectRelation ?? "")).localeCompare(b.subjectId + (b.subjectRelation ?? "")));
  emit({ op: "read", label: "read:document1-viewer", tuples });

  // ------------------------------------------------------------------
  // expand -- walk document:1#writer's tree by hand, following any
  // leaf.tupleToUserset pointer with a second Expand call.
  // ------------------------------------------------------------------
  const expandResp = unwrap(await raw.expand(STORE_ID, { tuple_key: { object: "document:1", relation: "writer" } }));
  const leafUsers = expandResp.tree?.root ? await collectLeafUsers(expandResp.tree.root) : [];
  emit({ op: "expand", label: "expand:document1-writer", leafUsers: leafUsers.sort() });
}

interface ExpandNode {
  leaf?: {
    users?: { users: string[] };
    tupleToUserset?: { tupleset: string; computed: { userset: string }[] };
  };
  union?: { nodes: ExpandNode[] };
}

async function collectLeafUsers(node: ExpandNode): Promise<string[]> {
  if (node.union) {
    const nested = await Promise.all(node.union.nodes.map(collectLeafUsers));
    return nested.flat();
  }
  if (node.leaf?.users) {
    return node.leaf.users.users.map((u) => u.split(":")[1]);
  }
  if (node.leaf?.tupleToUserset) {
    const out: string[] = [];
    for (const c of node.leaf.tupleToUserset.computed) {
      const [obj, relation] = c.userset.split("#");
      const resp = unwrap(await raw.expand(STORE_ID, { tuple_key: { object: obj, relation } }));
      if (resp.tree?.root) {
        out.push(...(await collectLeafUsers(resp.tree.root)));
      }
    }
    return out;
  }
  return [];
}

main().catch((err) => {
  console.error("FATAL:", err);
  process.exit(1);
});
